//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKalendarDesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liturgijska_boja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Liturgijska_boja()
        {
            this.Misa = new HashSet<Misa>();
        }
    
        public int IdLiturgijskaBoja { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public string ColorString { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Misa> Misa { get; set; }
    }
}
