//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKalendarDesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Misa
    {
        public int IdMisa { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public Nullable<int> IdRazinaSlavlja { get; set; }
        public Nullable<int> IdVrstaSlavlja { get; set; }
        public Nullable<int> IdLiturgijskaBoja { get; set; }
        public Nullable<int> IdVrijemeSlavlja { get; set; }
        public Nullable<int> IdCitanja { get; set; }
        public Nullable<int> IdNepromjenjivi { get; set; }
        public Nullable<int> IdPropriji { get; set; }
    
        public virtual Citanja Citanja { get; set; }
        public virtual Liturgijska_boja Liturgijska_boja { get; set; }
        public virtual Nepromjenjivi Nepromjenjivi { get; set; }
        public virtual Propriji Propriji { get; set; }
        public virtual Razina_slavlja Razina_slavlja { get; set; }
        public virtual Vrijeme_slavlja Vrijeme_slavlja { get; set; }
        public virtual Vrsta_slavlja Vrsta_slavlja { get; set; }
    }
}
