//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKalendarDesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tekst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tekst()
        {
            this.Citanja = new HashSet<Citanja>();
            this.Nepromjenjivi = new HashSet<Nepromjenjivi>();
            this.Propriji = new HashSet<Propriji>();
        }
    
        public int IdTekst { get; set; }
        public string Referenca { get; set; }
        public string Sadrzaj { get; set; }
        public int IdJezik { get; set; }
        public Nullable<int> IdVrstaTeksta { get; set; }
    
        public virtual Jezik Jezik { get; set; }
        public virtual Vrsta_teksta Vrsta_teksta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citanja> Citanja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nepromjenjivi> Nepromjenjivi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Propriji> Propriji { get; set; }
    }
}
